import Head from "next/head";
import Image from "next/image";
import classNames from "classnames";
import DownloadApp from "../components/DownloadApp";
import Hero from "../components/Hero";
import styles from "../styles/Home.module.css";
import discoverImage from "../public/screen-discover.png";
import connectImage from "../public/screen-connect.png";
import becomeImage from "../public/screen-become.png";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="preload"
          href="/fonts/RedHatDisplay/RedHatDisplay-Regular.ttf"
          as="font"
          crossOrigin=""
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      <main className={styles.main}>
        <p className={styles.accessible}>
          Stop wasting time trying to google it.
          <br />
          Connect with a pro who can help you immediately.
          <br />
          Real-time connections to skilled professionals around the country,
          that is Skillr.
        </p>
        <DownloadApp />

        <div className={styles.section}>
          <div className={styles.section__right}>
            <div>
              <Image src={discoverImage} alt="Discover Skillrs" />
            </div>
          </div>
          <div className={styles.section__left}>
            <div>
              <h2>Discover Skillrs</h2>
              <p>
                Connect with a professional at a moment&apos;s notice!
                <br />
                You now have professionals in your pocket.
              </p>
            </div>
          </div>
        </div>

        <div className={classNames(styles.section, styles.sectionConnect)}>
          <div className={styles.sectionConnectScreen}>
            <div>
              <Image src={connectImage} alt="One-Click Connect" />
            </div>
          </div>
          <div className={styles.section__left}>
            <div>
              <h2>One-Click Connect</h2>
              <p>
                Get instantly matched to professionals that can help you solve a
                problem, learn a skill, or just entertain you. Real-time
                connections, no waiting, no worries.
              </p>
            </div>
          </div>
        </div>

        <div className={styles.section}>
          <div className={styles.section__right}>
            <div>
              <Image src={becomeImage} alt="Become a Skillr" />
            </div>
          </div>
          <div className={styles.section__left}>
            <div>
              <h2>Become a Skillr</h2>
              <p>
                Are you a professional and want to make money from your skills?
                Apply to become a Skillr. Once approved you can set your own
                rate and begin monetizing your time while helping others.
              </p>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
