import Head from "next/head";
import Image from "next/image";
import DownloadApp from "../components/DownloadApp";
import Hero from "../components/Hero";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="preload"
          href="/fonts/RedHatDisplay/RedHatDisplay-Regular.ttf"
          as="font"
          crossOrigin=""
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      <main className={styles.main}>
        <h2 className={styles.accessible}>
          Skill sharing has never been more accessible —<br />to learners and
          skillrs alike.
        </h2>
        <DownloadApp />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
