import Head from "next/head";
import Image from "next/image";
import DownloadApp from "../components/DownloadApp";
import Hero from "../components/Hero";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="preload"
          href="/fonts/RedHatDisplay/RedHatDisplay-Regular.ttf"
          as="font"
          crossOrigin=""
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      <main className={styles.main}>
        <p className={styles.accessible}>
          Stop wasting time trying to google it.
          <br />
          Connect with a pro who can help you immediately.
          <br />
          Real-time connections to skilled professionals around the country,
          that is Skillr.
        </p>
        <DownloadApp />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
