name: "Deploy to S3"

on:
  push:
    branches:
    - staging
    # - production

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Set up vars
      id: vars
      run: |
        # Current branch name
        echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
        # echo ::set-output name=api_url::${case "${GITHUB_REF#refs/*/}" in production) echo "${GITHUB_REF#refs/*/}" ;; *) ;; esac }.skillr.com

    - name: Build
      run: yarn && yarn build && yarn export

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./out/ s3://${{ steps.vars.outputs.short_ref }}.skillr.com --delete